#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:

# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
i=0
while ((i < 8)); do 
	echo "Best School"
	if (( i == 2)); then
		echo "bad luck"
	elif ((i == 5)); then
		echo "good luck"
	fi
	((i+=1))
done
